const musicList = [
	{
		url: "./music/bensound-hey.mp3",
		title: "Hey",
		artist: "Ed Sheeran",
		artwork: require("./artworks/pexels-nikolaeva-nastia-10457501.jpg"),
		id: "1",
	},
	{
		url: "./music/bensound-happiness.mp3",
		title: "Happiness",
		artist: "Good Charlotte",
		artwork: require("./artworks/pexels-josh-sorenson-831889.jpg"),
		id: '2',
	},
	{
		url: "./music/bensound-theelevatorbossanova.mp3",
		title: "The Elevator Bossanova",
		artist: "Lauv",
		artwork: require("./artworks/pexels-pixabay-160722.jpg"),
		id: '3',
	},
	{
		url: "./music/bensound-adaytoremember.mp3",
		title: "A Day to Remember",
		artist: "Avril Lavigne",
		artwork: require("./artworks/pexels-mark-neal-3115006.jpg"),
		id: '4',
	},
	{
		url: "./music/bensound-dreams.mp3",
		title: "Dreams",
		artist: "Steriogram",
		artwork: require("./artworks/pexels-simon-berger-680562.jpg"),
		id: '5',
	},
	{
		url: "./music/bensound-erf.mp3",
		title: "ERF",
		artist: "아이유",
		artwork: require("./artworks/pexels-jill-burrow-6858673.jpg"),
		id: '6',
	},
	{
		url: "./music/bensound-perception.mp3",
		title: "Perception",
		artist: "AKMU",
		artwork: require("./artworks/pexels-moussa-idrissi-3694341.jpg"),
		id: '7',
	},
	{
		url: "./music/bensound-tenderness.mp3",
		title: "Tenderness",
		artist: "Lauv",
		artwork: require("./artworks/pexels-josh-sorenson-737552.jpg"),
		id: '8',
	},
	{
		url: "./music/bensound-anewbeginning.mp3",
		title: "A New Beginning",
		artist: "Anne Marie",
		artwork: require("./artworks/pexels-samuel-theo-manat-silitonga-848573.jpg"),
		id: '9',
	},
	{
		url: "./music/bensound-inspire.mp3",
		title: "Inspire",
		artist: "Lauv",
		artwork: require("./artworks/pexels-gelatin-6357186.jpg"),
		id: '10',
	},
	{
		url: "./music/bensound-tomorrow.mp3",
		title: "Tomorrow",
		artist: "Alan Walker, Noah Cyrus & Digital Farm Animals",
		artwork: require("./artworks/pexels-eberhard-grossgasteiger-2437286.jpg"),
		id: '11',
	},
	{
		url: "./music/bensound-onceagain.mp3",
		title: "Once Again",
		artist: "버스커 버스커",
		artwork: require("./artworks/pexels-samuel-theo-manat-silitonga-789555.jpg"),
		id: '12',
	},
	{
		url: "./music/bensound-memories.mp3",
		title: "Memories",
		artist: "Lauv",
		artwork: require("./artworks/pexels-ricardo-esquivel-1683492.jpg"),
		id: '13',
	},
	{
		url: "./music/bensound-creativeminds.mp3",
		title: "Creative Minds",
		artist: "Lauv",
		artwork: require("./artworks/pexels-min-an-1454789.jpg"),
		id: '14',
	},
	{
		url: "./music/bensound-clearday.mp3",
		title: "Clear Day",
		artist: "The Beatles",
		artwork: require("./artworks/pexels-aleksey-kuprikov-3493777.jpg"),
		id: '15',
	},
	{
		url: "./music/bensound-hey.mp3",
		title: "Hey",
		artist: "Ed Sheeran",
		artwork: require("./artworks/pexels-nikolaeva-nastia-10457501.jpg"),
		id: "21",
	},
	{
		url: "./music/bensound-happiness.mp3",
		title: "Happiness",
		artist: "Good Charlotte",
		artwork: require("./artworks/pexels-josh-sorenson-831889.jpg"),
		id: '22',
	},
	{
		url: "./music/bensound-theelevatorbossanova.mp3",
		title: "The Elevator Bossanova",
		artist: "Lauv",
		artwork: require("./artworks/pexels-pixabay-160722.jpg"),
		id: '23',
	},
	{
		url: "./music/bensound-adaytoremember.mp3",
		title: "A Day to Remember",
		artist: "Avril Lavigne",
		artwork: require("./artworks/pexels-mark-neal-3115006.jpg"),
		id: '24',
	},
	{
		url: "./music/bensound-dreams.mp3",
		title: "Dreams",
		artist: "Steriogram",
		artwork: require("./artworks/pexels-simon-berger-680562.jpg"),
		id: '25',
	},
	{
		url: "./music/bensound-erf.mp3",
		title: "ERF",
		artist: "아이유",
		artwork: require("./artworks/pexels-jill-burrow-6858673.jpg"),
		id: '26',
	},
	{
		url: "./music/bensound-perception.mp3",
		title: "Perception",
		artist: "AKMU",
		artwork: require("./artworks/pexels-moussa-idrissi-3694341.jpg"),
		id: '27',
	},
	{
		url: "./music/bensound-tenderness.mp3",
		title: "Tenderness",
		artist: "Lauv",
		artwork: require("./artworks/pexels-josh-sorenson-737552.jpg"),
		id: '28',
	},
	{
		url: "./music/bensound-anewbeginning.mp3",
		title: "A New Beginning",
		artist: "Anne Marie",
		artwork: require("./artworks/pexels-samuel-theo-manat-silitonga-848573.jpg"),
		id: '29',
	},
	{
		url: "./music/bensound-inspire.mp3",
		title: "Inspire",
		artist: "Lauv",
		artwork: require("./artworks/pexels-gelatin-6357186.jpg"),
		id: '210',
	},
	{
		url: "./music/bensound-tomorrow.mp3",
		title: "Tomorrow",
		artist: "Alan Walker, Noah Cyrus & Digital Farm Animals",
		artwork: require("./artworks/pexels-eberhard-grossgasteiger-2437286.jpg"),
		id: '211',
	},
	{
		url: "./music/bensound-onceagain.mp3",
		title: "Once Again",
		artist: "버스커 버스커",
		artwork: require("./artworks/pexels-samuel-theo-manat-silitonga-789555.jpg"),
		id: '212',
	},
	{
		url: "./music/bensound-memories.mp3",
		title: "Memories",
		artist: "Lauv",
		artwork: require("./artworks/pexels-ricardo-esquivel-1683492.jpg"),
		id: '213',
	},
	{
		url: "./music/bensound-creativeminds.mp3",
		title: "Creative Minds",
		artist: "Lauv",
		artwork: require("./artworks/pexels-min-an-1454789.jpg"),
		id: '214',
	},
	{
		url: "./music/bensound-clearday.mp3",
		title: "Clear Day",
		artist: "The Beatles",
		artwork: require("./artworks/pexels-aleksey-kuprikov-3493777.jpg"),
		id: '215',
	},
	{
		url: "./music/bensound-hey.mp3",
		title: "Hey",
		artist: "Ed Sheeran",
		artwork: require("./artworks/pexels-nikolaeva-nastia-10457501.jpg"),
		id: '51',
	},
	{
		url: "./music/bensound-happiness.mp3",
		title: "Happiness",
		artist: "Good Charlotte",
		artwork: require("./artworks/pexels-josh-sorenson-831889.jpg"),
		id: '52',
	},
	{
		url: "./music/bensound-theelevatorbossanova.mp3",
		title: "The Elevator Bossanova",
		artist: "Lauv",
		artwork: require("./artworks/pexels-pixabay-160722.jpg"),
		id: '53',
	},
	{
		url: "./music/bensound-adaytoremember.mp3",
		title: "A Day to Remember",
		artist: "Avril Lavigne",
		artwork: require("./artworks/pexels-mark-neal-3115006.jpg"),
		id: '54',
	},
	{
		url: "./music/bensound-dreams.mp3",
		title: "Dreams",
		artist: "Steriogram",
		artwork: require("./artworks/pexels-simon-berger-680562.jpg"),
		id: '55',
	},
	{
		url: "./music/bensound-erf.mp3",
		title: "ERF",
		artist: "아이유",
		artwork: require("./artworks/pexels-jill-burrow-6858673.jpg"),
		id: '56',
	},
	{
		url: "./music/bensound-perception.mp3",
		title: "Perception",
		artist: "AKMU",
		artwork: require("./artworks/pexels-moussa-idrissi-3694341.jpg"),
		id: '57',
	},
	{
		url: "./music/bensound-tenderness.mp3",
		title: "Tenderness",
		artist: "Lauv",
		artwork: require("./artworks/pexels-josh-sorenson-737552.jpg"),
		id: '58',
	},
	{
		url: "./music/bensound-anewbeginning.mp3",
		title: "A New Beginning",
		artist: "Anne Marie",
		artwork: require("./artworks/pexels-samuel-theo-manat-silitonga-848573.jpg"),
		id: '59',
	},
	{
		url: "./music/bensound-inspire.mp3",
		title: "Inspire",
		artist: "Lauv",
		artwork: require("./artworks/pexels-gelatin-6357186.jpg"),
		id: '510',
	},
	{
		url: "./music/bensound-tomorrow.mp3",
		title: "Tomorrow",
		artist: "Alan Walker, Noah Cyrus & Digital Farm Animals",
		artwork: require("./artworks/pexels-eberhard-grossgasteiger-2437286.jpg"),
		id: '511',
	},
	{
		url: "./music/bensound-onceagain.mp3",
		title: "Once Again",
		artist: "버스커 버스커",
		artwork: require("./artworks/pexels-samuel-theo-manat-silitonga-789555.jpg"),
		id: '512',
	},
	{
		url: "./music/bensound-memories.mp3",
		title: "Memories",
		artist: "Lauv",
		artwork: require("./artworks/pexels-ricardo-esquivel-1683492.jpg"),
		id: '513',
	},
	{
		url: "./music/bensound-creativeminds.mp3",
		title: "Creative Minds",
		artist: "Lauv",
		artwork: require("./artworks/pexels-min-an-1454789.jpg"),
		id: '514',
	},
	{
		url: "./music/bensound-clearday.mp3",
		title: "Clear Day",
		artist: "The Beatles",
		artwork: require("./artworks/pexels-aleksey-kuprikov-3493777.jpg"),
		id: '515',
	},
];

export default musicList;
