const musicList = [
	{
		uri: require("../assets/music/bensound-hey.mp3"),
		title: "Hey",
		artist: "Ed Sheeran",
		cover: require("../assets/cover/pexels-nikolaeva-nastia-10457501.jpg"),
		id: 1,
	},
	{
		uri: require("../assets/music/bensound-happiness.mp3"),
		title: "Happiness",
		artist: "Good Charlotte",
		cover: require("../assets/cover/pexels-josh-sorenson-831889.jpg"),
		id: 2,
	},
	{
		uri: require("../assets/music/bensound-theelevatorbossanova.mp3"),
		title: "The Elevator Bossanova",
		artist: "Lauv",
		cover: require("../assets/cover/pexels-pixabay-160722.jpg"),
		id: 3,
	},
	{
		uri: require("../assets/music/bensound-adaytoremember.mp3"),
		title: "A Day to Remember",
		artist: "Avril Lavigne",
		cover: require("../assets/cover/pexels-mark-neal-3115006.jpg"),
		id: 4,
	},
	{
		uri: require("../assets/music/bensound-dreams.mp3"),
		title: "Dreams",
		artist: "Steriogram",
		cover: require("../assets/cover/pexels-simon-berger-680562.jpg"),
		id: 5,
	},
	{
		uri: require("../assets/music/bensound-erf.mp3"),
		title: "ERF",
		artist: "아이유",
		cover: require("../assets/cover/pexels-jill-burrow-6858673.jpg"),
		id: 6,
	},
	{
		uri: require("../assets/music/bensound-perception.mp3"),
		title: "Perception",
		artist: "AKMU",
		cover: require("../assets/cover/pexels-moussa-idrissi-3694341.jpg"),
		id: 7,
	},
	{
		uri: require("../assets/music/bensound-tenderness.mp3"),
		title: "Tenderness",
		artist: "Lauv",
		cover: require("../assets/cover/pexels-josh-sorenson-737552.jpg"),
		id: 8,
	},
	{
		uri: require("../assets/music/bensound-anewbeginning.mp3"),
		title: "A New Beginning",
		artist: "Anne Marie",
		cover: require("../assets/cover/pexels-samuel-theo-manat-silitonga-848573.jpg"),
		id: 9,
	},
	{
		uri: require("../assets/music/bensound-inspire.mp3"),
		title: "Inspire",
		artist: "Lauv",
		cover: require("../assets/cover/pexels-gelatin-6357186.jpg"),
		id: 10,
	},
	{
		uri: require("../assets/music/bensound-tomorrow.mp3"),
		title: "Tomorrow",
		artist: "Alan Walker, Noah Cyrus & Digital Farm Animals",
		cover: require("../assets/cover/pexels-eberhard-grossgasteiger-2437286.jpg"),
		id: 11,
	},
	{
		uri: require("../assets/music/bensound-onceagain.mp3"),
		title: "Once Again",
		artist: "버스커 버스커",
		cover: require("../assets/cover/pexels-samuel-theo-manat-silitonga-789555.jpg"),
		id: 12,
	},
	{
		uri: require("../assets/music/bensound-memories.mp3"),
		title: "Memories",
		artist: "Lauv",
		cover: require("../assets/cover/pexels-ricardo-esquivel-1683492.jpg"),
		id: 13,
	},
	{
		uri: require("../assets/music/bensound-creativeminds.mp3"),
		title: "Creative Minds",
		artist: "Lauv",
		cover: require("../assets/cover/pexels-min-an-1454789.jpg"),
		id: 14,
	},
	{
		uri: require("../assets/music/bensound-clearday.mp3"),
		title: "Clear Day",
		artist: "The Beatles",
		cover: require("../assets/cover/pexels-aleksey-kuprikov-3493777.jpg"),
		id: 15,
	},
];

export default musicList;
